### ISSUE TITLE
InventorySingleton w/ List

### ISSUE THREAD

**Issue by drewburlingame** [gamosoft/Inventory-WebAPI#2]
what prompted the use of a List?  why not use a ConcurrentDictionary?

**Comment by gamosoft** [comment]
To be honest I’ve never used that type before, there are so many… :-)
Thinking about it I see it has thread-safe operations already built-in, and it could have been a better choice so I didn’t have to handle locks myself.
However, plain Dictionaries tend to be less performant (AFAIK). I initially tried with a HybridDictionary which performs well versus plain Dictionaries and Hashtables (best of both worlds) and I’ve used in the past but then opted for a more simpler approach just with a List<T> handling the thread-safe issues myself.
I can revert back to any of these other collections if you wish, however I’d still need to handle atomicity to send notifications and other stuff (as I have implemented with the “lock” regions).

**Comment by drewburlingame** [comment]
actually, dictionaries can be orders of magnitude faster for key lookups.  on one project i came into, they were using the .Where and .First linq methods all over and i converted the collection to dictionaries and batch processing time went from >10min to <10sec.

I'd challenge you to use the ConcurrentDictionary and see if it isn't the simpler approach.

**Comment by gamosoft** [comment]
Oh no, no, that's absolutely right, I'm afraid I didn't make myself clear enough. Keyed collections are better performing than lists, stacks, etc. What I mean is that Dictionaries alone are worse than HybridDictionaries in specific cases, no relation to Lists. I ended up using a List for commodity.
I have switched to a ConcurrentDictionary as you suggested instead. :-)
